apiVersion: v1
kind: Service
metadata:
  name: flash-service
  labels:
    app: flash
spec:
  type: NodePort
  selector:
    app: flash
  ports:
    - protocol: TCP
      port: 80            # Internal cluster port
      targetPort: 3000    # Container port where app listens
      nodePort: 30036     # External port accessible on node IP
