apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-deployment
  labels:
    app: flash
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flash
  template:
    metadata:
      labels:
        app: flash
    spec:
      containers:
      - name: flash
        image: docker.io/rvishrutha/my-react-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
